[package]
name = "vespr0/titanium"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
destruction = "A framework that implements common features for roblox games."

[dependencies]
fusion = "elttob/fusion@0.3.0" # WARNING: Don't switch to 0.4 until the code supports it.

# Melee
shapecasthitbox = "teamswordphin/shapecasthitbox@0.1.7"

# Network
BridgeNet2 = "ffrostflame/bridgenet2@^0.5"

# Voxel destruction
greedymeshing = "royal0959/rblx-nonvoxel-greedy-meshing@1.0.3"
partcache = "andremhpra/partcache@1.0.0"

# Datastore
suphisdatastoremodule = "skylord-103/suphisdatastoremodule@1.0.0"
